version: "3"

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  # Can't reach the API yet!
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 8080:80
