version: "3"

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - FRONTEND_API_URL=http://backend:8000
