---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: k8s-test
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: k8s-test
        tier: frontend
    spec:
      containers:
        - name: k8s-test-frontend
          image: "jagardaniel/k8s-test-frontend:latest"
          env:
            - name: SERVER_PORT
              value: 1338
            - name: API_URL
              value: http://backend
          ports:
            - containerPort: 1338
