name: Backend - Build and test
on:
  push:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build
        run: go build -v .
      - name: Run tests
        run: go test -v ./...
